export const skill =[
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Angular",
    "Vue",
    "Redux",
    "Webpack",
    "Babel",
    "Sass",
    "Less",
    "Styled-components",
    "Tailwind CSS",
    "Bootstrap",
    "Material-UI",
    "Jest",
    "Enzyme",
    "Mocha",
    "Chai",
    "Cypress",
    "Karma",
    "Progressive Web Apps (PWA)",
    "Responsive Web Design (RWD)",
    "Single Page Applications (SPA)",
    "Web Accessibility",
    "GraphQL",
    "Apollo Client",
    "Next.js",
    "Gatsby",
    "Frontend Performance Optimization",
    "Browser Compatibility",
    "Cross-browser Testing",
    "UI/UX Design",
    "Wireframing",
    "Prototyping",
    "User Testing",
    "Responsive Design Principles",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "ASP.NET",
    "Ruby on Rails",
    "Java",
    "Spring Boot",
    "Python",
    "PHP",
    "Laravel",
    "Symfony",
    "Ruby",
    "Scala",
    "Kotlin",
    "Microservices",
    "RESTful APIs",
    "GraphQL",
    "Serverless Framework",
    "NestJS",
    "FastAPI",
    "API Design",
    "Web Services",
    "Message Queues",
    "Service-Oriented Architecture (SOA)",
    "Backend Scalability",
    "Concurrency",
    "Load Balancing",
    "Caching Strategies",
    "AWS",
    "Amazon Web Services",
    "Azure",
    "Microsoft Azure",
    "Google Cloud Platform",
    "GCP",
    "Heroku",
    "DigitalOcean",
    "Vercel",
    "Netlify",
    "Firebase",
    "Cloud computing",
    "Serverless",
    "Containers",
    "Kubernetes",
    "Docker",
    "Terraform",
    "CloudFormation",
    "AWS Lambda",
    "AWS ECS",
    "AWS EC2",
    "Azure Functions",
    "Google App Engine",
    "Google Kubernetes Engine (GKE)",
    "Cloud Security Best Practices",
    "Cost Optimization",
    "Cloud Monitoring",
    "DevOps",
    "Continuous Integration (CI)",
    "Continuous Deployment (CD)",
    "CI/CD pipelines",
    "Automation",
    "Configuration management",
    "Infrastructure automation",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Puppet",
    "Chef",
    "Monitoring",
    "Logging",
    "Alerting",
    "ELK Stack",
    "Prometheus",
    "Grafana",
    "Infrastructure as Code (IaC)",
    "Container Orchestration",
    "Microservices Architecture",
    "Site Reliability Engineering (SRE)",
    "Software Development Life Cycle (SDLC)",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Lean Software Development",
    "Waterfall Model",
    "Software Architecture",
    "Design Patterns",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Code Refactoring",
    "Code Review",
    "Pair Programming",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Version Control",
    "Code Quality Assurance",
    "Technical Debt Management",
    "Software Documentation",
    "Software Requirements Specification (SRS)",
    "Software Design Document (SDD)",
    "Software Development Plan (SDP)",
    "Software Configuration Management",
    "Software Release Management",
    "Software Maintenance",
    "Software Deployment",
    "Software Performance Optimization",
    "Software Scalability",
    "Software Reliability",
    "Software Security",
    "Data science",
    "Machine learning",
    "Deep learning",
    "Natural Language Processing (NLP)",
    "Computer vision",
    "Big data",
    "Data analysis",
    "Data visualization",
    "Statistics",
    "Python",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Data Engineering",
    "Data Warehousing",
    "ETL (Extract, Transform, Load)",
    "Data Lakes",
    "Apache Spark",
    "Hadoop",
    "Apache Kafka",
    "Stream Processing",
    "Cybersecurity",
    "Information security",
    "Network security",
    "Application security",
    "Cloud security",
    "Penetration testing",
    "Vulnerability assessment",
    "Security compliance",
    "Security operations",
    "Identity and access management",
    "Security architecture",
    "Security engineering",
    "Security analysis",
    "Security auditing",
    "Security monitoring",
    "Security incident response",
    "Security awareness",
    "Security training",
    "Security policies",
    "Security procedures",
    "Security standards",
    "Security best practices",
    "Encryption",
    "SSL/TLS",
    "OAuth",
    "SAML",
    "OpenID Connect",
    "PKI (Public Key Infrastructure)",
    "Zero Trust Security",
    "Web Application Firewall (WAF)",
    "Mobile development",
    "iOS development",
    "Android development",
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Java",
    "Objective-C",
    "Xcode",
    "Android Studio",
    "Mobile UI design",
    "Mobile UX design",
    "Mobile app testing",
    "Mobile app deployment",
    "App Store",
    "Google Play Store",
    "Mobile app analytics",
    "Mobile app marketing",
    "Mobile app monetization",
    "Mobile app optimization",
    "Cross-platform development",
    "Native development",
    "Hybrid development", 
    "Database management",
    "SQL",
    "NoSQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "Oracle",
    "SQL Server",
    "MariaDB",
    "Cassandra",
    "DynamoDB",
    "Firebase Realtime Database",
    "Firebase Firestore",
    "T-SQL",
    "PL/SQL",
    "REST API",
    "GraphQL",
    "SOAP",
    "Database design",
    "Database administration",
    "Database optimization",
    "Database performance",
    "Database security",
    "Database scalability",
    "Database migration",
    "Database backup",
    "Database recovery",
    "Database monitoring",
    "Database tuning",
    "Database replication",
    "Database sharding",
    "Database clustering",
    "Database indexing",
    "Database normalization",
    "Database denormalization",
    "Database modeling",
    "Database schema",
    "Database query",
    "Database transaction",
    "Database trigger",
    "Database view",
    "Database stored procedure",
    "Database function",
    "Database join",
    "Database union",
    "Database intersection",
    "Database difference",
    "Database aggregation",
    "Data warehouse",
    "Data mart",
    "OLAP (Online Analytical Processing)",
    "OLTP (Online Transaction Processing)",
    "ACID (Atomicity, Consistency, Isolation, Durability)",
    "CAP Theorem",
    "Sharding",
    "Replication",
    "Federation",
    "Testing",
    "Unit testing",
    "Integration testing",
    "End-to-end testing",
    "Test automation",
    "Selenium",
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Karma",
    "Jasmine",
    "PHPUnit",
    "Mockito",
    "PowerMock",
    "EasyMock",
    "TestNG",
    "Robot Framework",
    "Cucumber",
    "Gherkin",
    "Behave",
    "RSpec",
    "Capybara",
    "SoapUI",
    "Postman",
    "JMeter",
    "LoadRunner",
    "Gatling",
    "TestRail",
    "TestLink",
    "Test management",
    "Test case",
    "Test plan",
    "Test strategy",
    "Test suite",
    "Test scenario",
    "Test script",
    "Test data",
    "Test environment",
    "Test coverage",
    "Code coverage",
    "Test report",
    "Test log",
    "Test result",
    "Test summary",
    "Business Intelligence",
    "Data Warehousing",
    "Data Mining",
    "Online Analytical Processing (OLAP)",
    "Data Visualization",
    "ETL (Extract, Transform, Load)",
    "Dashboard Development",
    "Reporting Tools",
    "Data Modeling",
    "Dimensional Modeling",
    "Business Analytics",
    "Predictive Analytics",
    "Big Data Analytics",
    "Data Quality Management",
    "Master Data Management (MDM)",
    "Key Performance Indicators (KPIs)",
    "Decision Support Systems (DSS)",
    "Business Process Monitoring",
    "Data Governance",
    "Data Integration",
    "Data Warehouse Automation",
    "Self-Service BI",
    "Data Discovery",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Natural Language Processing (NLP)",
    "Deep Learning",
    "Neural Networks",
    "Reinforcement Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Recommender Systems",
    "Cluster Analysis",
    "Anomaly Detection",
    "Sentiment Analysis",
    "Predictive Modeling",
    "Prescriptive Analytics",
    "Descriptive Analytics",
    "Diagnostic Analytics",
    "Big Data",
    "Hadoop",
    "Spark",
    "NoSQL",
    "SQL",
    "Python",
    "R Programming",
    "Tableau",
    "QlikView",
    "Power BI",
    "MicroStrategy",
    "IBM Cognos",
    "Oracle BI",
    "Pentaho",
    "Talend",
    "Informatica",
    "Domo",
    "RapidMiner",
    "Alteryx",
    "Looker",
    "Sisense",
    "Yellowfin",
    "GoodData",
    "Birst",
    "Spotfire",
    "DataRobot",
    "Domino Data Lab",
    "Rapid Insight",
    "TIBCO Spotfire",
    "SAP BusinessObjects",
    "Microsoft Power BI",
    "Google Data Studio",
    "Amazon QuickSight",
    "Dundas BI",
    "Zoho Analytics",
    "Pyramid Analytics",
    "SAP Analytics Cloud",
    "SAP Lumira",
    "SAP BW/4HANA",
    "SAP HANA",
    "SAP Business Warehouse",
    "SAP Data Services",
    "SAP Predictive Analytics",
    "SAP Analytics Hub",
    "SAP Business Planning and Consolidation",
    "Internet of Things (IoT)",
    "Embedded Systems",
    "Sensors",
    "Actuators",
    "IoT Platforms",
    "Edge Computing",
    "Smart Devices",
    "M2M (Machine-to-Machine) Communication",
    "IoT Security",
    "IoT Protocols",
    "Wireless Networking",
    "RFID (Radio-Frequency Identification)",
    "NFC (Near Field Communication)",
    "BLE (Bluetooth Low Energy)",
    "Zigbee",
    "LoRa",
    "MQTT",
    "CoAP",
    "Smart Cities",
    "Industrial IoT (IIoT)",
    "Home Automation",
    "Wearable Technology",
    "Healthcare IoT",
    "Agriculture IoT",
    "Automotive IoT",
    "Energy Management",
    "arduino",
    "raspberry pi",
    "IoT Data Analytics",
    "STM32",
    "ESP32",
    "IoT Cloud Platforms",
    "AWS IoT",
    "Azure IoT",
    "Google Cloud IoT",
    "IBM Watson IoT",
    "IoT Device Management",
    "IoT Firmware Development",
    "IoT Application Development",
    "IoT Connectivity Solutions",
    "IoT Gateway Development",
    "IoT Testing",
    "IoT Prototyping",
    "IoT Deployment",
    "IoT Monitoring",
    "IoT Maintenance",
    "IoT Troubleshooting",
    "IoT Security"
]